import { writeFile } from "fs/promises";
import { retrievePostSummaries } from "../src/lib/api";
import path from "path";

console.log("Generating tags...");

(async () => {
  const postSummaries = await retrievePostSummaries();
  const tagSet = new Set<string>(postSummaries.flatMap((post) => post.tags));

  const data = `// This file is generated by scripts/generate-tags.ts. DO NOT EDIT.

export const Tags = [
${[...tagSet]
  .sort()
  .map((tag) => `  "${tag}"`)
  .join(",\n")},
] as const;

export type Tag = typeof Tags[number];
`;

  await writeFile(path.join(process.cwd(), "src/generated/tags.ts"), data);

  console.log("Generated tags.");
})().catch((e) => {
  console.error(e);
});
