name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: corepack enable yarn
      - name: Cache yarn packages
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: node-cache-yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-cache-yarn-${{ runner.os }}-
      - run: yarn install
      - run: yarn lint
