name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
